name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Atualiza a cada 6 horas
  workflow_dispatch:        # Permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: maalineramos
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit e push do resultado
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
